# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

# Binaries
brew "bat" # "cat" on steroids
brew "git"
brew "grep"
brew "mackup"
brew "pkg-config" # Requested by other packages
brew "stow"

# Image Binaries
brew "jpegoptim"
brew "optipng"
brew "pngquant"
brew "svgo"
brew "gifsicle"

# Development
brew "nvm"

# Apps
cask "iterm2"
cask "keepassxc"
cask "caffeine"
cask "firefox"
cask "dropbox"
cask "google-backup-and-sync"
cask "google-chrome"
cask "imageoptim"
cask "phpstorm"
cask "skype"
cask "visual-studio-code"
cask "dbeaver-community"
cask "inkscape"