name: Dotfiles integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTFILES: ${{github.workspace}}

jobs:
  macos_bootstrap:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Unlink node if linked
      run: brew list -1 | grep node | while read line; do brew unlink $line; done 

    - name: Run bootstrap
      run: ./bootstrap -f
